version: 2

sources:
  - name: sap_adventure_works
    schema: sap_adw
    description: Fonte de dados de Pessoas do SAP Adeventure Works
    tables:
      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: personcreditcard
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

      - name: creditcard
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null        
     